import type { LoadedGameConfig } from '../../shared/types.js';

export function createKuaishouGameJson(loaded: LoadedGameConfig): {
  deviceOrientation: 'portrait' | 'landscape';
  showStatusBar: false;
} {
  return {
    deviceOrientation: loaded.game.orientation,
    showStatusBar: false,
  };
}

export function createKuaishouProjectConfigJson(loaded: LoadedGameConfig): {
  appid: string;
  projectname: string;
  setting: { es6: true };
  condition: Record<string, never>;
} {
  if (loaded.platform !== 'kuaishou' || !loaded.kuaishouMaterials) {
    throw new Error('createKuaishouProjectConfigJson requires a loaded kuaishou config');
  }
  return {
    appid: loaded.kuaishouMaterials.appid,
    projectname: loaded.kuaishouMaterials.projectName,
    setting: {
      es6: true,
    },
    condition: {},
  };
}

export function renderKuaishouGameJs(bundleCode: string, loaded: LoadedGameConfig): string {
  if (loaded.platform !== 'kuaishou' || !loaded.kuaishouMaterials) {
    throw new Error('renderKuaishouGameJs requires a loaded kuaishou config');
  }
  const rewardedAdUnitId = JSON.stringify(loaded.kuaishouMaterials.rewardedAdUnitId ?? '');
  return `/* Generated by mini-pack. */
(function () {
${bundleCode}

  function warn(message, data) {
    if (typeof console !== 'undefined' && typeof console.warn === 'function') {
      console.warn('[mini-pack]', message, data === undefined ? '' : data);
    }
  }

  function info(message, data) {
    if (typeof console !== 'undefined' && typeof console.info === 'function') {
      console.info('[mini-pack]', message, data === undefined ? '' : data);
    }
  }

  var root = typeof globalThis !== 'undefined' ? globalThis : this;
  var ks = root.ks || {};
  var rewardedAdUnitId = ${rewardedAdUnitId};
  var runtimeConfig = {
    platform: 'kuaishou',
    serverBaseUrl: ${JSON.stringify(loaded.game.serverBaseUrl ?? '')}
  };

  function createCanvas() {
    var canvas;
    if (ks && typeof ks.createCanvas === 'function') {
      canvas = ks.createCanvas();
      installTouchEventShim(canvas);
      return canvas;
    }
    if (root.canvas) {
      canvas = root.canvas;
      installTouchEventShim(canvas);
      return canvas;
    }
    if (typeof document !== 'undefined' && typeof document.createElement === 'function') {
      return document.createElement('canvas');
    }
    warn('Canvas API is unavailable; using a minimal fallback canvas.');
    return {
      width: 0,
      height: 0,
      getContext: function () {
        return null;
      }
    };
  }

  function installTouchEventShim(canvas) {
    if (!canvas || canvas.__miniPackTouchShimInstalled) {
      return;
    }

    canvas.__miniPackTouchShimInstalled = true;
    var nativeAddEventListener = typeof canvas.addEventListener === 'function' ? canvas.addEventListener.bind(canvas) : null;
    var nativeRemoveEventListener = typeof canvas.removeEventListener === 'function' ? canvas.removeEventListener.bind(canvas) : null;
    var eventMap = {
      pointerdown: ['onTouchStart', 'offTouchStart'],
      touchstart: ['onTouchStart', 'offTouchStart'],
      pointermove: ['onTouchMove', 'offTouchMove'],
      touchmove: ['onTouchMove', 'offTouchMove'],
      pointerup: ['onTouchEnd', 'offTouchEnd'],
      touchend: ['onTouchEnd', 'offTouchEnd'],
      pointercancel: ['onTouchCancel', 'offTouchCancel'],
      touchcancel: ['onTouchCancel', 'offTouchCancel']
    };
    var listeners = {};

    canvas.addEventListener = function (type, listener) {
      var mapping = eventMap[type];
      if (typeof listener !== 'function') {
        return;
      }

      if (!mapping) {
        if (nativeAddEventListener) {
          nativeAddEventListener(type, listener);
        }
        return;
      }

      var onName = mapping[0];
      if (typeof ks[onName] !== 'function') {
        if (nativeAddEventListener) {
          nativeAddEventListener(type, listener);
          return;
        }
        warn('Touch API is unavailable: ' + onName);
        return;
      }

      listeners[type] = listeners[type] || [];
      listeners[type].push(listener);
      ks[onName](listener);
    };

    canvas.removeEventListener = function (type, listener) {
      var mapping = eventMap[type];
      if (!mapping) {
        if (nativeRemoveEventListener && typeof listener === 'function') {
          nativeRemoveEventListener(type, listener);
        }
        return;
      }

      var list = listeners[type] || [];
      var index = list.indexOf(listener);
      if (index >= 0) {
        list.splice(index, 1);
      }

      var offName = mapping[1];
      if (typeof ks[offName] === 'function') {
        ks[offName](listener);
      }
    };
  }

  var storage = {
    getString: function (key) {
      try {
        if (typeof ks.getStorageSync === 'function') {
          var value = ks.getStorageSync(key);
          return typeof value === 'string' ? value : null;
        }
        if (root.localStorage) {
          return root.localStorage.getItem(key);
        }
      } catch (error) {
        warn('Storage get failed.', error);
      }
      return null;
    },
    setString: function (key, value) {
      try {
        if (typeof ks.setStorageSync === 'function') {
          ks.setStorageSync(key, value);
          return;
        }
        if (root.localStorage) {
          root.localStorage.setItem(key, value);
        }
      } catch (error) {
        warn('Storage set failed.', error);
      }
    },
    remove: function (key) {
      try {
        if (typeof ks.removeStorageSync === 'function') {
          ks.removeStorageSync(key);
          return;
        }
        if (root.localStorage) {
          root.localStorage.removeItem(key);
        }
      } catch (error) {
        warn('Storage remove failed.', error);
      }
    }
  };

  var muted = false;
  var sfxAudio = null;
  var musicAudio = null;

  function createAudioContext(label) {
    if (!ks || typeof ks.createInnerAudioContext !== 'function') {
      warn(label + ' audio API is unavailable.');
      return null;
    }

    var context = ks.createInnerAudioContext();
    if (context) {
      context.obeyMuteSwitch = false;
      if (typeof context.onError === 'function') {
        context.onError(function (error) {
          warn(label + ' audio playback failed.', error);
        });
      }
    }
    return context;
  }

  function sfxPath(name) {
    return 'assets/audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.wav';
  }

  function musicPath(name) {
    return 'assets/audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.mp3';
  }

  var audio = {
    playSfx: function (name) {
      if (muted) {
        return Promise.resolve();
      }

      try {
        sfxAudio = sfxAudio || createAudioContext('SFX');
        if (!sfxAudio) {
          return Promise.resolve();
        }
        if (typeof sfxAudio.stop === 'function') {
          try {
            sfxAudio.stop();
          } catch (error) {
            warn('Stopping SFX audio failed.', error);
          }
        }
        sfxAudio.src = sfxPath(name);
        if (typeof sfxAudio.play === 'function') {
          sfxAudio.play();
        }
      } catch (error) {
        warn('SFX playback failed.', error);
      }
      return Promise.resolve();
    },
    playMusic: function (name, loop) {
      if (muted) {
        return Promise.resolve();
      }

      try {
        musicAudio = musicAudio || createAudioContext('Music');
        if (!musicAudio) {
          return Promise.resolve();
        }
        musicAudio.loop = Boolean(loop);
        musicAudio.src = musicPath(name);
        if (typeof musicAudio.play === 'function') {
          musicAudio.play();
        }
      } catch (error) {
        warn('Music playback failed.', error);
      }
      return Promise.resolve();
    },
    stopMusic: function () {
      if (musicAudio && typeof musicAudio.stop === 'function') {
        try {
          musicAudio.stop();
        } catch (error) {
          warn('Stopping music failed.', error);
        }
      }
    },
    setMuted: function (nextMuted) {
      muted = Boolean(nextMuted);
      if (muted) {
        this.stopMusic();
        if (sfxAudio && typeof sfxAudio.stop === 'function') {
          try {
            sfxAudio.stop();
          } catch (error) {
            warn('Stopping SFX audio failed.', error);
          }
        }
      }
    }
  };

  var rewardedVideoAd = null;

  function getRewardedVideoAd() {
    if (!rewardedAdUnitId || typeof ks.createRewardedVideoAd !== 'function') {
      return null;
    }
    if (!rewardedVideoAd) {
      rewardedVideoAd = ks.createRewardedVideoAd({ adUnitId: rewardedAdUnitId });
      if (rewardedVideoAd && typeof rewardedVideoAd.onError === 'function') {
        rewardedVideoAd.onError(function (error) {
          warn('Rewarded video ad failed.', error);
        });
      }
    }
    return rewardedVideoAd;
  }

  function showRewardedVideoAd() {
    var ad = getRewardedVideoAd();
    if (!ad) {
      warn('Rewarded video API is unavailable or ad unit id is missing.');
      return Promise.resolve({ completed: false });
    }

    return new Promise(function (resolve) {
      var settled = false;
      var onClose = function (result) {
        if (settled) return;
        settled = true;
        if (typeof ad.offClose === 'function') {
          ad.offClose(onClose);
        }
        resolve({ completed: result === undefined || Boolean(result && result.isEnded) });
      };
      var onError = function (error) {
        if (settled) return;
        settled = true;
        if (typeof ad.offClose === 'function') {
          ad.offClose(onClose);
        }
        if (typeof ad.offError === 'function') {
          ad.offError(onError);
        }
        warn('Rewarded video playback failed.', error);
        resolve({ completed: false });
      };

      if (typeof ad.onClose === 'function') {
        ad.onClose(onClose);
      }
      if (typeof ad.onError === 'function') {
        ad.onError(onError);
      }

      try {
        Promise.resolve(typeof ad.show === 'function' ? ad.show() : null).catch(onError);
      } catch (error) {
        onError(error);
      }
    });
  }

  var ads = {
    isRewardedVideoReady: function () {
      return Boolean(rewardedAdUnitId && typeof ks.createRewardedVideoAd === 'function');
    },
    showRewardedVideo: function () {
      return showRewardedVideoAd();
    }
  };

  function canUseApi(name) {
    if (!ks || typeof ks[name] !== 'function') {
      return false;
    }
    if (typeof ks.canIUse !== 'function') {
      return true;
    }
    try {
      return Boolean(ks.canIUse(name));
    } catch (error) {
      warn('Checking API availability failed: ' + name, error);
      return true;
    }
  }

  var auth = {
    login: function () {
      return new Promise(function (resolve, reject) {
        if (typeof ks.login !== 'function') {
          reject(new Error('Kuaishou login API is unavailable.'));
          return;
        }

        try {
          ks.login({
            success: function (result) {
              var code = result && typeof result.code === 'string' ? result.code : '';
              if (!code) {
                reject(new Error('Kuaishou login did not return a code.'));
                return;
              }
              resolve({ platform: 'kuaishou', code: code });
            },
            fail: function (error) {
              reject(error || new Error('Kuaishou login failed.'));
            }
          });
        } catch (error) {
          reject(error);
        }
      });
    }
  };

  var net = {
    request: function (options) {
      return new Promise(function (resolve, reject) {
        if (!options || !options.url) {
          reject(new Error('Request url is required.'));
          return;
        }
        if (typeof ks.request !== 'function') {
          reject(new Error('Kuaishou request API is unavailable.'));
          return;
        }

        try {
          ks.request({
            url: options.url,
            method: options.method || 'GET',
            data: options.data,
            header: options.headers || {},
            success: function (result) {
              resolve({
                status: result && typeof result.statusCode === 'number' ? result.statusCode : 0,
                data: result ? result.data : null,
                headers: result ? result.header || result.headers || {} : {}
              });
            },
            fail: function (error) {
              reject(error || new Error('Kuaishou request failed.'));
            }
          });
        } catch (error) {
          reject(error);
        }
      });
    }
  };

  function callKuaishouApi(name) {
    return new Promise(function (resolve) {
      var api = ks && ks[name];
      if (typeof api !== 'function') {
        resolve({ ok: false, result: null });
        return;
      }

      var settled = false;
      var finish = function (ok, result) {
        if (settled) {
          return;
        }
        settled = true;
        resolve({ ok: ok, result: result || null });
      };
      var success = function (result) {
        finish(true, result);
      };
      var fail = function (error) {
        warn('Kuaishou API failed: ' + name, error);
        finish(false, error);
      };

      try {
        api({
          success: success,
          fail: fail,
          complete: function () {}
        });
      } catch (objectStyleError) {
        try {
          api(success, fail);
        } catch (callbackStyleError) {
          warn('Kuaishou API threw: ' + name, callbackStyleError);
          finish(false, callbackStyleError);
        }
      }
    });
  }

  function parseShortcutInstalled(result) {
    if (!result) {
      return false;
    }
    if (typeof result.installed === 'boolean') {
      return result.installed;
    }
    if (typeof result.exist === 'boolean') {
      return result.exist;
    }
    if (typeof result.exists === 'boolean') {
      return result.exists;
    }
    return false;
  }

  function parseCommonUse(result) {
    if (!result) {
      return false;
    }
    if (typeof result.isCommonUse === 'boolean') {
      return result.isCommonUse;
    }
    if (typeof result.commonUse === 'boolean') {
      return result.commonUse;
    }
    if (typeof result.added === 'boolean') {
      return result.added;
    }
    return false;
  }

  function checkShortcutExists() {
    if (typeof ks.checkShortcut !== 'function') {
      return Promise.resolve(null);
    }
    return callKuaishouApi('checkShortcut').then(function (result) {
      return result.ok ? parseShortcutInstalled(result.result) : null;
    });
  }

  function addDesktopShortcut() {
    if (typeof ks.addShortcut !== 'function') {
      return Promise.resolve(false);
    }
    return callKuaishouApi('addShortcut').then(function (result) {
      return result.ok;
    });
  }

  function checkCommonUseExists() {
    if (typeof ks.checkCommonUse !== 'function') {
      return Promise.resolve(null);
    }
    return callKuaishouApi('checkCommonUse').then(function (result) {
      return result.ok ? parseCommonUse(result.result) : null;
    });
  }

  function addCommonUse() {
    if (typeof ks.addCommonUse !== 'function') {
      return Promise.resolve(false);
    }
    return callKuaishouApi('addCommonUse').then(function (result) {
      return result.ok;
    });
  }

  var rewards = {
    canAddDesktop: function () {
      return Promise.resolve(canUseApi('addShortcut') || canUseApi('checkShortcut'));
    },
    requestAddDesktop: function () {
      return checkShortcutExists().then(function (exists) {
        if (exists === true) {
          return true;
        }
        return addDesktopShortcut().then(function (added) {
          if (!added) {
            return false;
          }
          return checkShortcutExists().then(function (nextExists) {
            return nextExists === true || added;
          });
        });
      });
    },
    canAddFavorite: function () {
      return Promise.resolve(canUseApi('addCommonUse') || canUseApi('checkCommonUse'));
    },
    requestAddFavorite: function () {
      return checkCommonUseExists().then(function (exists) {
        if (exists === true) {
          return true;
        }
        return addCommonUse().then(function (added) {
          if (!added) {
            return false;
          }
          return checkCommonUseExists().then(function (nextExists) {
            return nextExists === true || added;
          });
        });
      });
    },
    didEnterFromSidebar: function () {
      return Promise.resolve(false);
    },
    requestSidebarEntry: function () {
      return Promise.resolve(false);
    }
  };

  var haptics = {
    trigger: function (kind) {
      var apiName = kind === 'long' ? 'vibrateLong' : 'vibrateShort';
      var api = ks && ks[apiName];
      var data = { kind: kind, apiName: apiName, supported: typeof api === 'function' };
      info('Haptic platform call.', data);

      if (typeof api !== 'function') {
        warn('Haptic platform API unavailable.', data);
        return;
      }

      try {
        api({
          success: function (result) {
            info('Haptic platform success.', { kind: kind, apiName: apiName, result: result });
          },
          fail: function (error) {
            warn('Haptic platform failed.', { kind: kind, apiName: apiName, error: error });
          },
          complete: function (result) {
            info('Haptic platform complete.', { kind: kind, apiName: apiName, result: result });
          }
        });
      } catch (error) {
        warn('Haptic platform threw.', { kind: kind, apiName: apiName, error: error });
      }
    }
  };

  var logger = {
    info: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.info === 'function') console.info(message, data);
    },
    warn: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.warn === 'function') console.warn(message, data);
    },
    error: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.error === 'function') console.error(message, data);
    }
  };

  var createGame = __MiniPackGameBundle && __MiniPackGameBundle.createGame;
  if (typeof createGame !== 'function') {
    throw new Error('Game entry must export createGame(runtime).');
  }

  var app = createGame({
    canvas: createCanvas(),
    config: runtimeConfig,
    storage: storage,
    audio: audio,
    auth: auth,
    net: net,
    ads: ads,
    rewards: rewards,
    haptics: haptics,
    logger: logger
  });
  root.__MiniPackGameApp = app;
  app.start();
})();
`;
}
