import type { LoadedGameConfig } from '../../shared/types.js';

export function createGameJson(loaded: LoadedGameConfig): { deviceOrientation: 'portrait' | 'landscape'; showStatusBar: false } {
  return {
    deviceOrientation: loaded.game.orientation,
    showStatusBar: false,
  };
}

export function createProjectConfigJson(loaded: LoadedGameConfig): {
  appid: string;
  projectname: string;
  setting: { es6: true };
  condition: Record<string, never>;
} {
  if (loaded.platform !== 'douyin' || !loaded.douyinMaterials) {
    throw new Error('createProjectConfigJson requires a loaded douyin config');
  }
  return {
    appid: loaded.douyinMaterials.appid,
    projectname: loaded.douyinMaterials.projectName,
    setting: {
      es6: true,
    },
    condition: {},
  };
}

export function renderDouyinGameJs(bundleCode: string, loaded: LoadedGameConfig): string {
  if (loaded.platform !== 'douyin' || !loaded.douyinMaterials) {
    throw new Error('renderDouyinGameJs requires a loaded douyin config');
  }
  const rewardedAdUnitId = JSON.stringify(loaded.douyinMaterials.rewardedAdUnitId ?? '');
  return `/* Generated by mini-pack. */
(function () {
${bundleCode}

  function warn(message, data) {
    if (typeof console !== 'undefined' && typeof console.warn === 'function') {
      console.warn('[mini-pack]', message, data === undefined ? '' : data);
    }
  }

  function info(message, data) {
    if (typeof console !== 'undefined' && typeof console.info === 'function') {
      console.info('[mini-pack]', message, data === undefined ? '' : data);
    }
  }

  var root = typeof globalThis !== 'undefined' ? globalThis : this;
  var tt = root.tt || {};
  var rewardedAdUnitId = ${rewardedAdUnitId};

  function createCanvas() {
    var canvas;
    if (tt && typeof tt.createCanvas === 'function') {
      canvas = tt.createCanvas();
      installTouchEventShim(canvas);
      return canvas;
    }
    if (root.canvas) {
      canvas = root.canvas;
      installTouchEventShim(canvas);
      return canvas;
    }
    if (typeof document !== 'undefined' && typeof document.createElement === 'function') {
      return document.createElement('canvas');
    }
    warn('Canvas API is unavailable; using a minimal fallback canvas.');
    return {
      width: 0,
      height: 0,
      getContext: function () {
        return null;
      }
    };
  }

  function installTouchEventShim(canvas) {
    if (!canvas || canvas.__miniPackTouchShimInstalled) {
      return;
    }

    canvas.__miniPackTouchShimInstalled = true;
    var nativeAddEventListener = typeof canvas.addEventListener === 'function' ? canvas.addEventListener.bind(canvas) : null;
    var nativeRemoveEventListener = typeof canvas.removeEventListener === 'function' ? canvas.removeEventListener.bind(canvas) : null;
    var eventMap = {
      pointerdown: ['onTouchStart', 'offTouchStart'],
      touchstart: ['onTouchStart', 'offTouchStart'],
      pointermove: ['onTouchMove', 'offTouchMove'],
      touchmove: ['onTouchMove', 'offTouchMove'],
      pointerup: ['onTouchEnd', 'offTouchEnd'],
      touchend: ['onTouchEnd', 'offTouchEnd'],
      pointercancel: ['onTouchCancel', 'offTouchCancel'],
      touchcancel: ['onTouchCancel', 'offTouchCancel']
    };
    var listeners = {};

    canvas.addEventListener = function (type, listener) {
      var mapping = eventMap[type];
      if (typeof listener !== 'function') {
        return;
      }

      if (!mapping) {
        if (nativeAddEventListener) {
          nativeAddEventListener(type, listener);
        }
        return;
      }

      var onName = mapping[0];
      if (typeof tt[onName] !== 'function') {
        if (nativeAddEventListener) {
          nativeAddEventListener(type, listener);
          return;
        }
        warn('Touch API is unavailable: ' + onName);
        return;
      }

      listeners[type] = listeners[type] || [];
      listeners[type].push(listener);
      tt[onName](listener);
    };

    canvas.removeEventListener = function (type, listener) {
      var mapping = eventMap[type];
      if (!mapping) {
        if (nativeRemoveEventListener && typeof listener === 'function') {
          nativeRemoveEventListener(type, listener);
        }
        return;
      }

      var list = listeners[type] || [];
      var index = list.indexOf(listener);
      if (index >= 0) {
        list.splice(index, 1);
      }

      var offName = mapping[1];
      if (typeof tt[offName] === 'function') {
        tt[offName](listener);
      }
    };
  }

  var storage = {
    getString: function (key) {
      try {
        if (typeof tt.getStorageSync === 'function') {
          var value = tt.getStorageSync(key);
          return typeof value === 'string' ? value : null;
        }
        if (root.localStorage) {
          return root.localStorage.getItem(key);
        }
      } catch (error) {
        warn('Storage get failed.', error);
      }
      return null;
    },
    setString: function (key, value) {
      try {
        if (typeof tt.setStorageSync === 'function') {
          tt.setStorageSync(key, value);
          return;
        }
        if (root.localStorage) {
          root.localStorage.setItem(key, value);
        }
      } catch (error) {
        warn('Storage set failed.', error);
      }
    },
    remove: function (key) {
      try {
        if (typeof tt.removeStorageSync === 'function') {
          tt.removeStorageSync(key);
          return;
        }
        if (root.localStorage) {
          root.localStorage.removeItem(key);
        }
      } catch (error) {
        warn('Storage remove failed.', error);
      }
    }
  };

  var muted = false;
  var sfxAudio = null;
  var musicAudio = null;

  function createAudioContext(label) {
    if (!tt || typeof tt.createInnerAudioContext !== 'function') {
      warn(label + ' audio API is unavailable.');
      return null;
    }

    var context = tt.createInnerAudioContext();
    if (context) {
      context.obeyMuteSwitch = false;
      if (typeof context.onError === 'function') {
        context.onError(function (error) {
          warn(label + ' audio playback failed.', error);
        });
      }
    }
    return context;
  }

  function sfxPath(name) {
    return 'assets/audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.wav';
  }

  function musicPath(name) {
    return 'assets/audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.mp3';
  }

  var audio = {
    playSfx: function (name) {
      if (muted) {
        return Promise.resolve();
      }

      try {
        sfxAudio = sfxAudio || createAudioContext('SFX');
        if (!sfxAudio) {
          return Promise.resolve();
        }
        if (typeof sfxAudio.stop === 'function') {
          try {
            sfxAudio.stop();
          } catch (error) {
            warn('Stopping SFX audio failed.', error);
          }
        }
        sfxAudio.src = sfxPath(name);
        if (typeof sfxAudio.play === 'function') {
          sfxAudio.play();
        }
      } catch (error) {
        warn('SFX playback failed.', error);
      }
      return Promise.resolve();
    },
    playMusic: function (name, loop) {
      if (muted) {
        return Promise.resolve();
      }

      try {
        musicAudio = musicAudio || createAudioContext('Music');
        if (!musicAudio) {
          return Promise.resolve();
        }
        musicAudio.loop = Boolean(loop);
        musicAudio.src = musicPath(name);
        if (typeof musicAudio.play === 'function') {
          musicAudio.play();
        }
      } catch (error) {
        warn('Music playback failed.', error);
      }
      return Promise.resolve();
    },
    stopMusic: function () {
      if (musicAudio && typeof musicAudio.stop === 'function') {
        try {
          musicAudio.stop();
        } catch (error) {
          warn('Stopping music failed.', error);
        }
      }
    },
    setMuted: function (nextMuted) {
      muted = Boolean(nextMuted);
      if (muted) {
        this.stopMusic();
        if (sfxAudio && typeof sfxAudio.stop === 'function') {
          try {
            sfxAudio.stop();
          } catch (error) {
            warn('Stopping SFX audio failed.', error);
          }
        }
      }
    }
  };

  var rewardedVideoAd = null;

  function getRewardedVideoAd() {
    if (!rewardedAdUnitId || typeof tt.createRewardedVideoAd !== 'function') {
      return null;
    }
    if (!rewardedVideoAd) {
      rewardedVideoAd = tt.createRewardedVideoAd({ adUnitId: rewardedAdUnitId });
      if (rewardedVideoAd && typeof rewardedVideoAd.onError === 'function') {
        rewardedVideoAd.onError(function (error) {
          warn('Rewarded video ad failed.', error);
        });
      }
    }
    return rewardedVideoAd;
  }

  function showRewardedVideoAd() {
    var ad = getRewardedVideoAd();
    if (!ad) {
      warn('Rewarded video API is unavailable or ad unit id is missing.');
      return Promise.resolve({ completed: false });
    }

    return new Promise(function (resolve) {
      var settled = false;
      var onClose = function (result) {
        if (settled) return;
        settled = true;
        if (typeof ad.offClose === 'function') {
          ad.offClose(onClose);
        }
        resolve({ completed: Boolean(result && result.isEnded) });
      };
      var onError = function (error) {
        if (settled) return;
        settled = true;
        if (typeof ad.offClose === 'function') {
          ad.offClose(onClose);
        }
        if (typeof ad.offError === 'function') {
          ad.offError(onError);
        }
        warn('Rewarded video playback failed.', error);
        resolve({ completed: false });
      };

      if (typeof ad.onClose === 'function') {
        ad.onClose(onClose);
      }
      if (typeof ad.onError === 'function') {
        ad.onError(onError);
      }

      var showResult;
      try {
        showResult = typeof ad.show === 'function' ? ad.show() : null;
      } catch (error) {
        onError(error);
        return;
      }

      Promise.resolve(showResult).catch(function () {
        if (typeof ad.load !== 'function') {
          onError(new Error('Rewarded video show failed.'));
          return;
        }
        Promise.resolve(ad.load())
          .then(function () {
            return ad.show();
          })
          .catch(onError);
      });
    });
  }

  var ads = {
    isRewardedVideoReady: function () {
      return Boolean(rewardedAdUnitId && typeof tt.createRewardedVideoAd === 'function');
    },
    showRewardedVideo: function () {
      return showRewardedVideoAd();
    }
  };

  var enteredFromSidebar = false;

  function readLaunchOptions(name) {
    try {
      return typeof tt[name] === 'function' ? tt[name]() : null;
    } catch (error) {
      warn('Reading ' + name + ' failed.', error);
      return null;
    }
  }

  function isSidebarEntry(options) {
    if (!options) {
      return false;
    }

    var query = options.query || {};
    return options.scene === '021036' ||
      options.scene === 'sidebar' ||
      (options.launch_from === 'homepage' && options.location === 'sidebar_card') ||
      (query.launch_from === 'homepage' && query.location === 'sidebar_card') ||
      query.from === 'sidebar';
  }

  function rememberSidebarEntry(options) {
    if (isSidebarEntry(options)) {
      enteredFromSidebar = true;
    }
  }

  rememberSidebarEntry(readLaunchOptions('getEnterOptionsSync'));
  rememberSidebarEntry(readLaunchOptions('getLaunchOptionsSync'));
  if (typeof tt.onShow === 'function') {
    tt.onShow(function (options) {
      rememberSidebarEntry(options);
    });
  }

  function canUseApi(name) {
    if (!tt || typeof tt[name] !== 'function') {
      return false;
    }
    if (typeof tt.canIUse !== 'function') {
      return true;
    }
    try {
      return Boolean(tt.canIUse(name));
    } catch (error) {
      warn('Checking API availability failed: ' + name, error);
      return true;
    }
  }

  function parseShortcutExists(result) {
    if (typeof result === 'boolean') {
      return result;
    }
    if (!result) {
      return false;
    }
    if (typeof result.exist === 'boolean') {
      return result.exist;
    }
    if (result.status && typeof result.status.exist === 'boolean') {
      return result.status.exist;
    }
    return false;
  }

  function checkShortcutExists() {
    if (typeof tt.checkShortcut !== 'function') {
      return Promise.resolve(null);
    }

    return new Promise(function (resolve) {
      try {
        tt.checkShortcut(function (result) {
          resolve(parseShortcutExists(result));
        });
      } catch (error) {
        warn('Checking desktop shortcut failed.', error);
        resolve(null);
      }
    });
  }

  function addDesktopShortcut() {
    if (typeof tt.addShortcut !== 'function') {
      return Promise.resolve(false);
    }

    return new Promise(function (resolve) {
      try {
        tt.addShortcut(function (result) {
          if (result === undefined) {
            resolve(true);
            return;
          }
          resolve(result !== false);
        });
      } catch (error) {
        warn('Adding desktop shortcut failed.', error);
        resolve(false);
      }
    });
  }

  function showFavoriteGuide() {
    if (typeof tt.showFavoriteGuide !== 'function') {
      return Promise.resolve(false);
    }

    return new Promise(function (resolve) {
      try {
        tt.showFavoriteGuide({
          type: 'bar',
          content: '添加到常用',
          position: 'bottom',
          success: function () {
            resolve(true);
          },
          fail: function (error) {
            warn('Showing favorite guide failed.', error);
            resolve(false);
          }
        });
      } catch (error) {
        warn('Showing favorite guide failed.', error);
        resolve(false);
      }
    });
  }

  var rewards = {
    canAddDesktop: function () {
      return Promise.resolve(canUseApi('addShortcut') || canUseApi('checkShortcut'));
    },
    requestAddDesktop: function () {
      return checkShortcutExists().then(function (exists) {
        if (exists === true) {
          return true;
        }
        return addDesktopShortcut().then(function (added) {
          if (added) {
            return true;
          }
          return checkShortcutExists().then(function (nextExists) {
            return nextExists === true;
          });
        });
      });
    },
    canAddFavorite: function () {
      return Promise.resolve(canUseApi('showFavoriteGuide'));
    },
    requestAddFavorite: function () {
      return showFavoriteGuide();
    },
    didEnterFromSidebar: function () {
      rememberSidebarEntry(readLaunchOptions('getEnterOptionsSync'));
      rememberSidebarEntry(readLaunchOptions('getLaunchOptionsSync'));
      return Promise.resolve(enteredFromSidebar);
    },
    requestSidebarEntry: function () {
      if (typeof tt.navigateToScene !== 'function') {
        warn('Sidebar API is unavailable: navigateToScene');
        return Promise.resolve(false);
      }

      return new Promise(function (resolve) {
        try {
          tt.navigateToScene({
            scene: 'sidebar',
            success: function () {
              resolve(true);
            },
            fail: function (error) {
              warn('Navigating to sidebar failed.', error);
              resolve(false);
            }
          });
        } catch (error) {
          warn('Navigating to sidebar failed.', error);
          resolve(false);
        }
      });
    }
  };

  var haptics = {
    trigger: function (kind) {
      var apiName = kind === 'long' ? 'vibrateLong' : 'vibrateShort';
      var api = tt && tt[apiName];
      var data = { kind: kind, apiName: apiName, supported: typeof api === 'function' };
      info('Haptic platform call.', data);

      if (typeof api !== 'function') {
        warn('Haptic platform API unavailable.', data);
        return;
      }

      try {
        api({
          success: function (result) {
            info('Haptic platform success.', { kind: kind, apiName: apiName, result: result });
          },
          fail: function (error) {
            warn('Haptic platform failed.', { kind: kind, apiName: apiName, error: error });
          },
          complete: function (result) {
            info('Haptic platform complete.', { kind: kind, apiName: apiName, result: result });
          }
        });
      } catch (error) {
        warn('Haptic platform threw.', { kind: kind, apiName: apiName, error: error });
      }
    }
  };

  var logger = {
    info: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.info === 'function') console.info(message, data);
    },
    warn: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.warn === 'function') console.warn(message, data);
    },
    error: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.error === 'function') console.error(message, data);
    }
  };

  var createGame = __MiniPackGameBundle && __MiniPackGameBundle.createGame;
  if (typeof createGame !== 'function') {
    throw new Error('Game entry must export createGame(runtime).');
  }

  var app = createGame({
    canvas: createCanvas(),
    storage: storage,
    audio: audio,
    ads: ads,
    rewards: rewards,
    haptics: haptics,
    logger: logger
  });
  root.__MiniPackGameApp = app;
  app.start();
})();
`;
}
