import path from 'node:path';

import type { LoadedGameConfig } from '../../shared/types.js';

export const VIVO_CLI_VERSION = '1.27.23';
export const VIVO_ICON_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAkElEQVR4nO3QQQ0AIBDAMMC/5+ONAvZoFSzZnJLNejvdAdy9A3gMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaAxoDGgMaOxUu4MfQ7jBC+QAAAAASUVORK5CYII=';

export function createVivoPackageJson(): Record<string, unknown> {
  return {
    name: 'qgame',
    version: '1.0.0',
    private: true,
    scripts: {
      build: 'mgs build',
      release: 'mgs release',
      watch: 'mgs watch',
      server: 'mgs server',
    },
    devDependencies: {
      '@vivo-minigame/cli': VIVO_CLI_VERSION,
    },
  };
}

export function createVivoManifest(loaded: LoadedGameConfig): Record<string, unknown> {
  if (loaded.platform !== 'vivo' || !loaded.vivoMaterials) {
    throw new Error('createVivoManifest requires a loaded vivo config');
  }
  const { vivoMaterials, game } = loaded;
  return {
    package: vivoMaterials.packageName,
    name: game.title,
    versionName: vivoMaterials.versionName,
    versionCode: vivoMaterials.versionCode,
    minPlatformVersion: 1060,
    deviceOrientation: game.orientation,
    type: 'game',
    icon: '/icon.png',
    config: {
      logLevel: 'debug',
    },
  };
}

export function createVivoPackageName(projectRoot: string): string {
  const slug = path
    .basename(projectRoot)
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
  return `com.minipack.${slug || 'game'}`;
}

export function createVivoMainJs(): string {
  return `require("runtime-adapter/ral.js");
require("runtime-adapter/web-adapter.js");
require("game.js");
`;
}

export function createVivoRuntimeRalJs(): string {
  return `/* Minimal vivo runtime adapter generated by mini-pack. */
(function () {
  var root = typeof globalThis !== 'undefined' ? globalThis : this;
  var windowTarget = root.window && typeof root.window === 'object' ? root.window : root;
  var qg = root.qg || windowTarget.qg || {};
  var ral = root.ral || {};
  root.ral = windowTarget.ral = ral;

  function define(target, key, value) {
    if (!target || value === undefined) return;
    try {
      target[key] = value;
    } catch (error) {
      try {
        Object.defineProperty(target, key, {
          configurable: true,
          get: function () { return value; }
        });
      } catch (defineError) {}
    }
  }

  define(windowTarget, 'devicePixelRatio', 1);
  define(root, 'devicePixelRatio', 1);

  if (!windowTarget.mainCanvas && !root.mainCanvas && typeof qg.createCanvas === 'function') {
    var mainCanvas = qg.createCanvas();
    define(root, 'mainCanvas', mainCanvas);
    define(windowTarget, 'mainCanvas', mainCanvas);
    define(root, 'canvas', mainCanvas);
    define(windowTarget, 'canvas', mainCanvas);
    if (mainCanvas && !mainCanvas.style) {
      try { mainCanvas.style = {}; } catch (error) {}
    }
    if (mainCanvas && mainCanvas.constructor) {
      define(root, 'HTMLCanvasElement', mainCanvas.constructor);
      define(windowTarget, 'HTMLCanvasElement', mainCanvas.constructor);
    }
  }

  if (typeof qg.getCanvasRenderingContext2D === 'function') {
    try {
      var Context2D = qg.getCanvasRenderingContext2D();
      define(root, 'CanvasRenderingContext2D', Context2D);
      define(windowTarget, 'CanvasRenderingContext2D', Context2D);
    } catch (error) {}
  }

  if (typeof qg.createCanvas === 'function') {
    ral.createCanvas = qg.createCanvas.bind(qg);
  }
  if (typeof qg.createImage === 'function') {
    ral.createImage = qg.createImage.bind(qg);
  }
  if (typeof qg.getSystemInfoSync === 'function') {
    ral.getSystemInfoSync = function () {
      return qg.getSystemInfoSync();
    };
  }
})();
`;
}

export function createVivoRuntimeWebAdapterJs(): string {
  return `/* Minimal DOM adapter generated by mini-pack for vivo. */
(function () {
  var root = typeof globalThis !== 'undefined' ? globalThis : this;
  var documentRef = root.document;
  if (!documentRef) return;

  function createElementFallback(tagName) {
    return {
      tagName: String(tagName || '').toUpperCase(),
      style: {},
      children: [],
      appendChild: function (child) {
        this.children.push(child);
        if (child) child.parentNode = this;
        return child;
      },
      removeChild: function (child) {
        var index = this.children.indexOf(child);
        if (index >= 0) this.children.splice(index, 1);
        if (child && child.parentNode === this) child.parentNode = null;
        return child;
      }
    };
  }

  if (!documentRef.createElement) {
    documentRef.createElement = createElementFallback;
  }
  if (!documentRef.documentElement) {
    documentRef.documentElement = createElementFallback('html');
  }
  if (!documentRef.body) {
    documentRef.body = createElementFallback('body');
  }
})();
`;
}

export function renderVivoGameJs(bundleCode: string, loaded?: LoadedGameConfig): string {
  return `/* Generated by mini-pack for vivo. */
(function () {
  function warn(message, data) {
    if (typeof console !== 'undefined' && typeof console.warn === 'function') {
      console.warn('[mini-pack:vivo]', message, data === undefined ? '' : data);
    }
  }

  function info(message, data) {
    if (typeof console !== 'undefined' && typeof console.info === 'function') {
      console.info('[mini-pack:vivo]', message, data === undefined ? '' : data);
    }
  }

  var root = typeof globalThis !== 'undefined' ? globalThis : this;
  var windowTarget = root.window && typeof root.window === 'object' ? root.window : root;
  var qg = root.qg || windowTarget.qg || {};
  var runtimeConfig = {
    platform: 'vivo',
    serverBaseUrl: ${JSON.stringify(loaded?.game.serverBaseUrl ?? '')}${
    loaded?.vivoMaterials?.packageName
      ? `,\n    pkgName: ${JSON.stringify(loaded.vivoMaterials.packageName)}`
      : ''
  }
  };
  var bootDebugVersion = '2026-05-11-vivo-webgl-1';
  var bootStep = 0;
  var bootLogAllow = {
    'script entered': true,
    'createGame missing': true,
    'app.start error': true
  };

  function bootLog(label, value) {
    if (typeof console === 'undefined' || typeof console.log !== 'function') return;
    if (!bootLogAllow[label]) return;
    try {
      bootStep++;
      var step = bootStep < 10 ? '0' + bootStep : String(bootStep);
      var suffix = '';
      if (value !== undefined) {
        if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
          suffix = ' ' + String(value);
        } else {
          try {
            suffix = ' ' + JSON.stringify(value);
          } catch (error) {
            suffix = ' <unserializable>';
          }
        }
      }
      console.log('[mini-pack:vivo:boot] #' + step + ' ' + label + suffix);
    } catch (error) {}
  }

  bootLog('script entered', { version: bootDebugVersion });
  bootLog('globals', {
    hasWindow: !!root.window,
    rootIsWindow: root === windowTarget,
    hasDocument: typeof document !== 'undefined',
    hasRAF: typeof root.requestAnimationFrame,
    hasSetTimeout: typeof root.setTimeout,
    hasQG: !!qg,
    hasRootMainCanvas: !!root.mainCanvas,
    hasWindowMainCanvas: !!windowTarget.mainCanvas
  });

  var auth = {
    login: function () {
      return new Promise(function (resolve, reject) {
        if (typeof qg.login !== 'function') {
          reject(new Error('vivo login API is unavailable.'));
          return;
        }
        try {
          qg.login({
            success: function (result) {
              var code = result && typeof result.code === 'string' ? result.code : '';
              if (!code && result && typeof result.token === 'string') {
                code = result.token;
              }
              if (!code) {
                reject(new Error('vivo login did not return a code.'));
                return;
              }
              resolve({ platform: 'vivo', code: code });
            },
            fail: function (error) {
              reject(error || new Error('vivo login failed.'));
            }
          });
        } catch (error) {
          reject(error);
        }
      });
    }
  };

  var net = {
    request: function (options) {
      return new Promise(function (resolve, reject) {
        if (!options || !options.url) {
          reject(new Error('Request url is required.'));
          return;
        }
        if (typeof qg.request !== 'function') {
          reject(new Error('vivo request API is unavailable.'));
          return;
        }
        try {
          qg.request({
            url: options.url,
            method: options.method || 'GET',
            data: options.data,
            header: options.headers || {},
            success: function (result) {
              resolve({
                status: result && typeof result.statusCode === 'number' ? result.statusCode : 0,
                data: result ? result.data : null,
                headers: result ? result.header || result.headers || {} : {}
              });
            },
            fail: function (error) {
              reject(error || new Error('vivo request failed.'));
            }
          });
        } catch (error) {
          reject(error);
        }
      });
    }
  };
  bootLog('qg api', {
    createCanvas: typeof qg.createCanvas,
    createImage: typeof qg.createImage,
    getCanvasRenderingContext2D: typeof qg.getCanvasRenderingContext2D,
    getSystemInfoSync: typeof qg.getSystemInfoSync,
    onTouchStart: typeof qg.onTouchStart,
    createInnerAudioContext: typeof qg.createInnerAudioContext
  });
  if (typeof qg.getSystemInfoSync === 'function') {
    try {
      var sys = qg.getSystemInfoSync();
      bootLog('system info compact', sys ? {
        screenWidth: sys.screenWidth,
        screenHeight: sys.screenHeight,
        windowWidth: sys.windowWidth,
        windowHeight: sys.windowHeight,
        pixelRatio: sys.pixelRatio,
        platformVersionCode: sys.platformVersionCode,
        version: sys.miniGame && sys.miniGame.version
      } : null);
    } catch (error) {
      bootLog('system info error', String(error && (error.message || error)));
    }
  }

  function defineGlobalValue(target, key, value) {
    if (!target || value === undefined) {
      return;
    }
    try {
      target[key] = value;
    } catch (error) {
      try {
        Object.defineProperty(target, key, {
          configurable: true,
          get: function () {
            return value;
          }
        });
      } catch (defineError) {
        warn('Global export failed: ' + key, defineError);
      }
    }
  }

  // vivo runtime 不提供 web 标准 Image 构造函数；桥接到 qg.createImage 以便
  // 游戏代码里的 new Image() 能正常加载 .rpk 内资源。
  bootLog('image polyfill begin', {
    rootImage: typeof root.Image,
    windowImage: typeof windowTarget.Image,
    htmlImage: typeof windowTarget.HTMLImageElement
  });
  var ExistingImage = root.Image || windowTarget.Image;
  if (typeof ExistingImage === 'undefined' && typeof qg.createImage === 'function') {
    ExistingImage = function MiniPackVivoImage() {
      bootLog('Image constructor qg.createImage before');
      return qg.createImage();
    };
  }
  if (ExistingImage) {
    defineGlobalValue(root, 'Image', ExistingImage);
    defineGlobalValue(windowTarget, 'Image', ExistingImage);
  }
  bootLog('image polyfill done', {
    rootImage: typeof root.Image,
    windowImage: typeof windowTarget.Image,
    htmlImage: typeof windowTarget.HTMLImageElement
  });

  function createCanvas() {
    var canvas;
    bootLog('createCanvas begin');
    if (windowTarget.mainCanvas) {
      canvas = windowTarget.mainCanvas;
      bootLog('createCanvas source', 'window.mainCanvas');
      return canvas;
    }
    if (root.mainCanvas) {
      canvas = root.mainCanvas;
      bootLog('createCanvas source', 'root.mainCanvas');
      return canvas;
    }
    if (windowTarget.canvas) {
      canvas = windowTarget.canvas;
      bootLog('createCanvas source', 'window.canvas');
      return canvas;
    }
    if (root.canvas) {
      canvas = root.canvas;
      bootLog('createCanvas source', 'root.canvas');
      return canvas;
    }
    if (qg && typeof qg.createCanvas === 'function') {
      bootLog('qg.createCanvas before');
      canvas = qg.createCanvas();
      bootLog('qg.createCanvas after', {
        ok: !!canvas,
        ctor: canvas && canvas.constructor && canvas.constructor.name,
        width: canvas && canvas.width,
        height: canvas && canvas.height
      });
      return canvas;
    }
    if (typeof document !== 'undefined' && typeof document.createElement === 'function') {
      bootLog('createCanvas source', 'document.createElement');
      return document.createElement('canvas');
    }
    warn('Canvas API is unavailable; using a minimal fallback canvas.');
    return {
      width: 0,
      height: 0,
      getContext: function () {
        return null;
      }
    };
  }

  function installCanvasGlobals(canvas) {
    bootLog('installCanvasGlobals begin', { hasCanvas: !!canvas });
    if (!canvas) {
      return;
    }
    if (!canvas.style) {
      try {
        canvas.style = {};
      } catch (error) {}
    }
    if (typeof qg.getCanvasRenderingContext2D === 'function') {
      try {
        bootLog('getCanvasRenderingContext2D before');
        var Context2D = qg.getCanvasRenderingContext2D();
        bootLog('getCanvasRenderingContext2D after', { type: typeof Context2D });
        defineGlobalValue(root, 'CanvasRenderingContext2D', Context2D);
        defineGlobalValue(windowTarget, 'CanvasRenderingContext2D', Context2D);
      } catch (error) {
        warn('CanvasRenderingContext2D export failed.', error);
      }
    }
    if (canvas.constructor) {
      defineGlobalValue(root, 'HTMLCanvasElement', canvas.constructor);
      defineGlobalValue(windowTarget, 'HTMLCanvasElement', canvas.constructor);
    }
    defineGlobalValue(root, 'mainCanvas', canvas);
    defineGlobalValue(windowTarget, 'mainCanvas', canvas);
    if (!root.canvas) defineGlobalValue(root, 'canvas', canvas);
    if (!windowTarget.canvas) defineGlobalValue(windowTarget, 'canvas', canvas);
    bootLog('installCanvasGlobals done', {
      rootMainCanvas: root.mainCanvas === canvas,
      windowMainCanvas: windowTarget.mainCanvas === canvas,
      rootCanvas: root.canvas === canvas,
      windowCanvas: windowTarget.canvas === canvas
    });
  }

  function attachCanvasToDocument(canvas) {
    bootLog('attachCanvasToDocument begin', {
      hasCanvas: !!canvas,
      hasDocument: typeof document !== 'undefined',
      hasBody: typeof document !== 'undefined' && !!document.body
    });
    if (!canvas || typeof document === 'undefined' || !document.body) {
      return;
    }
    try {
      var style = canvas.style || (canvas.style = {});
      style.position = 'fixed';
      style.left = '0px';
      style.top = '0px';
      style.width = '100%';
      style.height = '100%';
      style.display = 'block';
      style.zIndex = '1';
      if (document.documentElement && document.documentElement.style) {
        document.documentElement.style.margin = '0';
        document.documentElement.style.padding = '0';
        document.documentElement.style.width = '100%';
        document.documentElement.style.height = '100%';
      }
      if (document.body.style) {
        document.body.style.margin = '0';
        document.body.style.padding = '0';
        document.body.style.width = '100%';
        document.body.style.height = '100%';
        document.body.style.overflow = 'hidden';
        document.body.style.background = 'transparent';
      }
      if (canvas.parentNode !== document.body && typeof document.body.appendChild === 'function') {
        document.body.appendChild(canvas);
      }
      bootLog('attachCanvasToDocument done', {
        parentIsBody: canvas.parentNode === document.body,
        bodyChildren: document.body.children && document.body.children.length,
        stylePosition: style.position,
        styleWidth: style.width,
        styleHeight: style.height,
        styleZIndex: style.zIndex
      });
    } catch (error) {
      bootLog('attachCanvasToDocument error', {
        message: String(error && (error.message || error)),
        stack: error && error.stack
      });
    }
  }

  var __miniPackCanvas = createCanvas();
  installCanvasGlobals(__miniPackCanvas);
  attachCanvasToDocument(__miniPackCanvas);
  bootLog('canvas exposed before bundle', {
    ctor: __miniPackCanvas && __miniPackCanvas.constructor && __miniPackCanvas.constructor.name,
    width: __miniPackCanvas && __miniPackCanvas.width,
    height: __miniPackCanvas && __miniPackCanvas.height,
    hasGetContext: __miniPackCanvas && typeof __miniPackCanvas.getContext === 'function',
    hasAddEventListener: __miniPackCanvas && typeof __miniPackCanvas.addEventListener === 'function',
    rootMainCanvas: root.mainCanvas === __miniPackCanvas,
    windowMainCanvas: windowTarget.mainCanvas === __miniPackCanvas,
    rootCanvas: root.canvas === __miniPackCanvas,
    windowCanvas: windowTarget.canvas === __miniPackCanvas
  });
  try {
    var __miniPackBootCtx = __miniPackCanvas && typeof __miniPackCanvas.getContext === 'function'
      ? __miniPackCanvas.getContext('2d')
      : null;
    bootLog('ctx before bundle', {
      ok: !!__miniPackBootCtx,
      ctor: __miniPackBootCtx && __miniPackBootCtx.constructor && __miniPackBootCtx.constructor.name,
      hasFillRect: __miniPackBootCtx && typeof __miniPackBootCtx.fillRect === 'function',
      hasDrawImage: __miniPackBootCtx && typeof __miniPackBootCtx.drawImage === 'function'
    });
  } catch (error) {
    bootLog('ctx before bundle error', String(error && (error.message || error)));
  }

${bundleCode}

  bootLog('bundle executed', {
    hasMiniPackBundle: !!__MiniPackGameBundle,
    createGameType: typeof (__MiniPackGameBundle && __MiniPackGameBundle.createGame)
  });

  var memoryStorage = {};
  var storage = {
    getString: function (key) {
      try {
        if (typeof qg.getStorageSync === 'function') {
          var value = qg.getStorageSync(key);
          return typeof value === 'string' ? value : null;
        }
        if (root.localStorage) {
          return root.localStorage.getItem(key);
        }
      } catch (error) {
        warn('Storage get failed.', error);
      }
      return Object.prototype.hasOwnProperty.call(memoryStorage, key) ? memoryStorage[key] : null;
    },
    setString: function (key, value) {
      try {
        if (typeof qg.setStorageSync === 'function') {
          qg.setStorageSync(key, value);
          return;
        }
        if (root.localStorage) {
          root.localStorage.setItem(key, value);
          return;
        }
      } catch (error) {
        warn('Storage set failed.', error);
      }
      memoryStorage[key] = value;
    },
    remove: function (key) {
      try {
        if (typeof qg.removeStorageSync === 'function') {
          qg.removeStorageSync(key);
          return;
        }
        if (root.localStorage) {
          root.localStorage.removeItem(key);
          return;
        }
      } catch (error) {
        warn('Storage remove failed.', error);
      }
      delete memoryStorage[key];
    }
  };

  var muted = false;
  var sfxAudio = null;
  var musicAudio = null;

  function createAudioContext(label) {
    if (!qg || typeof qg.createInnerAudioContext !== 'function') {
      warn(label + ' audio API is unavailable.');
      return null;
    }
    var context = qg.createInnerAudioContext();
    if (context && typeof context.onError === 'function') {
      context.onError(function (error) {
        warn(label + ' audio playback failed.', error);
      });
    }
    return context;
  }

  // public-pack 平铺到 .rpk 根后，audio 资源在 audio/...（不再加 assets/ 前缀）
  function sfxPath(name) {
    return 'audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.wav';
  }

  function musicPath(name) {
    return 'audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.mp3';
  }

  var audio = {
    playSfx: function (name) {
      if (muted) {
        return Promise.resolve();
      }
      try {
        sfxAudio = sfxAudio || createAudioContext('SFX');
        if (!sfxAudio) {
          return Promise.resolve();
        }
        if (typeof sfxAudio.stop === 'function') {
          sfxAudio.stop();
        }
        sfxAudio.src = sfxPath(name);
        if (typeof sfxAudio.play === 'function') {
          sfxAudio.play();
        }
      } catch (error) {
        warn('SFX playback failed.', error);
      }
      return Promise.resolve();
    },
    playMusic: function (name, loop) {
      if (muted) {
        return Promise.resolve();
      }
      try {
        musicAudio = musicAudio || createAudioContext('Music');
        if (!musicAudio) {
          return Promise.resolve();
        }
        musicAudio.loop = Boolean(loop);
        musicAudio.src = musicPath(name);
        if (typeof musicAudio.play === 'function') {
          musicAudio.play();
        }
      } catch (error) {
        warn('Music playback failed.', error);
      }
      return Promise.resolve();
    },
    stopMusic: function () {
      if (musicAudio && typeof musicAudio.stop === 'function') {
        try {
          musicAudio.stop();
        } catch (error) {
          warn('Stopping music failed.', error);
        }
      }
    },
    setMuted: function (nextMuted) {
      muted = Boolean(nextMuted);
      if (muted) {
        this.stopMusic();
        if (sfxAudio && typeof sfxAudio.stop === 'function') {
          try {
            sfxAudio.stop();
          } catch (error) {
            warn('Stopping SFX audio failed.', error);
          }
        }
      }
    }
  };

  var rewardedVideoAd = null;
  function getRewardedVideoAd() {
    if (typeof qg.createRewardedVideoAd !== 'function') {
      return null;
    }
    if (!rewardedVideoAd) {
      rewardedVideoAd = qg.createRewardedVideoAd({});
      if (rewardedVideoAd && typeof rewardedVideoAd.onError === 'function') {
        rewardedVideoAd.onError(function (error) {
          warn('Rewarded video ad failed.', error);
        });
      }
    }
    return rewardedVideoAd;
  }

  var ads = {
    isRewardedVideoReady: function () {
      return typeof qg.createRewardedVideoAd === 'function';
    },
    showRewardedVideo: function () {
      var ad = getRewardedVideoAd();
      if (!ad) {
        warn('Rewarded video API is unavailable.');
        return Promise.resolve({ completed: false });
      }
      return new Promise(function (resolve) {
        var settled = false;
        function cleanup() {
          if (typeof ad.offClose === 'function') {
            ad.offClose(onClose);
          }
          if (typeof ad.offError === 'function') {
            ad.offError(onError);
          }
        }
        var onClose = function (result) {
          if (settled) return;
          settled = true;
          cleanup();
          resolve({ completed: Boolean(result && result.isEnded) });
        };
        var onError = function (error) {
          if (settled) return;
          settled = true;
          cleanup();
          warn('Rewarded video playback failed.', error);
          resolve({ completed: false });
        };
        if (typeof ad.onClose === 'function') {
          ad.onClose(onClose);
        }
        if (typeof ad.onError === 'function') {
          ad.onError(onError);
        }
        if (typeof ad.show !== 'function') {
          onError(new Error('Rewarded video show API unavailable.'));
          return;
        }
        try {
          Promise.resolve(ad.show()).catch(function () {
            if (typeof ad.load !== 'function') {
              onError(new Error('Rewarded video load API unavailable.'));
              return;
            }
            Promise.resolve(ad.load()).then(function () {
              return ad.show();
            }).catch(onError);
          });
        } catch (error) {
          onError(error);
        }
      });
    }
  };

  var rewards = {
    canAddDesktop: function () { return Promise.resolve(false); },
    requestAddDesktop: function () { return Promise.resolve(false); },
    canAddFavorite: function () { return Promise.resolve(false); },
    requestAddFavorite: function () { return Promise.resolve(false); },
    didEnterFromSidebar: function () { return Promise.resolve(false); },
    requestSidebarEntry: function () { return Promise.resolve(false); }
  };

  var haptics = {
    trigger: function (kind) {
      var apiName = kind === 'long' ? 'vibrateLong' : 'vibrateShort';
      var api = qg && qg[apiName];
      if (typeof api !== 'function') {
        warn('Haptic platform API unavailable.', { kind: kind, apiName: apiName });
        return;
      }
      try {
        api({
          success: function (result) {
            info('Haptic platform success.', { kind: kind, apiName: apiName, result: result });
          },
          fail: function (error) {
            warn('Haptic platform failed.', { kind: kind, apiName: apiName, error: error });
          }
        });
      } catch (error) {
        warn('Haptic platform threw.', { kind: kind, apiName: apiName, error: error });
      }
    }
  };

  var logger = {
    info: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.info === 'function') console.info(message, data);
    },
    warn: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.warn === 'function') console.warn(message, data);
    },
    error: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.error === 'function') console.error(message, data);
    }
  };

  var createGame = __MiniPackGameBundle && __MiniPackGameBundle.createGame;
  if (typeof createGame !== 'function') {
    bootLog('createGame missing', { bundleKeys: __MiniPackGameBundle ? Object.keys(__MiniPackGameBundle) : null });
    throw new Error('Game entry must export createGame(runtime).');
  }

  bootLog('createGame calling');
  var app = createGame({
    canvas: __miniPackCanvas,
    config: runtimeConfig,
    storage: storage,
    audio: audio,
    auth: auth,
    net: net,
    ads: ads,
    rewards: rewards,
    haptics: haptics,
    logger: logger,
    createCanvas: qg && typeof qg.createCanvas === 'function' ? qg.createCanvas.bind(qg) : undefined,
    renderMode: 'webgl'
  });
  root.__MiniPackGameApp = app;
  windowTarget.__MiniPackGameApp = app;
  bootLog('createGame returned', {
    hasApp: !!app,
    startType: app && typeof app.start,
    pauseType: app && typeof app.pause,
    resumeType: app && typeof app.resume
  });
  try {
    app.start();
    bootLog('app.start ok');
  } catch (error) {
    bootLog('app.start error', {
      message: String(error && (error.message || error)),
      stack: error && error.stack
    });
    throw error;
  }
})();
`;
}
