import path from 'node:path';

import type { LoadedGameConfig } from '../../shared/types.js';

const VIVO_CLI_VERSION = '1.27.13';

export function createVivoPackageJson(): Record<string, unknown> {
  return {
    name: 'qgame',
    version: '1.0.0',
    private: true,
    scripts: {
      build: 'mg-service build',
      release: 'mg-service release',
      watch: 'mg-service watch',
      server: 'mg-service server',
    },
    devDependencies: {
      '@vivo-minigame/cli-service': VIVO_CLI_VERSION,
    },
  };
}

export function createVivoManifest(config: LoadedGameConfig): Record<string, unknown> {
  return {
    package: createVivoPackageName(config.douyin.projectName),
    name: config.title,
    versionName: '1.0.0',
    versionCode: 1,
    minPlatformVersion: 1060,
    deviceOrientation: config.orientation,
    type: 'game',
    config: {
      logLevel: 'debug',
    },
  };
}

export function createVivoPackageName(projectRoot: string): string {
  const slug = path
    .basename(projectRoot)
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
  return `com.minipack.${slug || 'game'}`;
}

export function renderVivoGameJs(bundleCode: string): string {
  return `/* Generated by mini-pack for vivo. */
(function () {
${bundleCode}

  function warn(message, data) {
    if (typeof console !== 'undefined' && typeof console.warn === 'function') {
      console.warn('[mini-pack:vivo]', message, data === undefined ? '' : data);
    }
  }

  function info(message, data) {
    if (typeof console !== 'undefined' && typeof console.info === 'function') {
      console.info('[mini-pack:vivo]', message, data === undefined ? '' : data);
    }
  }

  var root = typeof globalThis !== 'undefined' ? globalThis : this;
  var qg = root.qg || {};

  function createCanvas() {
    var canvas;
    if (qg && typeof qg.createCanvas === 'function') {
      canvas = qg.createCanvas();
      installTouchEventShim(canvas);
      return canvas;
    }
    if (root.canvas) {
      canvas = root.canvas;
      installTouchEventShim(canvas);
      return canvas;
    }
    if (typeof document !== 'undefined' && typeof document.createElement === 'function') {
      return document.createElement('canvas');
    }
    warn('Canvas API is unavailable; using a minimal fallback canvas.');
    return {
      width: 0,
      height: 0,
      getContext: function () {
        return null;
      }
    };
  }

  function installTouchEventShim(canvas) {
    if (!canvas || canvas.__miniPackVivoTouchShimInstalled) {
      return;
    }
    canvas.__miniPackVivoTouchShimInstalled = true;
    var nativeAddEventListener = typeof canvas.addEventListener === 'function' ? canvas.addEventListener.bind(canvas) : null;
    var nativeRemoveEventListener = typeof canvas.removeEventListener === 'function' ? canvas.removeEventListener.bind(canvas) : null;
    var eventMap = {
      pointerdown: ['onTouchStart', 'offTouchStart'],
      touchstart: ['onTouchStart', 'offTouchStart'],
      pointermove: ['onTouchMove', 'offTouchMove'],
      touchmove: ['onTouchMove', 'offTouchMove'],
      pointerup: ['onTouchEnd', 'offTouchEnd'],
      touchend: ['onTouchEnd', 'offTouchEnd'],
      pointercancel: ['onTouchCancel', 'offTouchCancel'],
      touchcancel: ['onTouchCancel', 'offTouchCancel']
    };
    var listeners = {};

    canvas.addEventListener = function (type, listener) {
      var mapping = eventMap[type];
      if (typeof listener !== 'function') {
        return;
      }
      if (!mapping) {
        if (nativeAddEventListener) {
          nativeAddEventListener(type, listener);
        }
        return;
      }
      var onName = mapping[0];
      if (typeof qg[onName] !== 'function') {
        if (nativeAddEventListener) {
          nativeAddEventListener(type, listener);
          return;
        }
        warn('Touch API is unavailable: ' + onName);
        return;
      }
      listeners[type] = listeners[type] || [];
      listeners[type].push(listener);
      qg[onName](listener);
    };

    canvas.removeEventListener = function (type, listener) {
      var mapping = eventMap[type];
      if (!mapping) {
        if (nativeRemoveEventListener && typeof listener === 'function') {
          nativeRemoveEventListener(type, listener);
        }
        return;
      }
      var list = listeners[type] || [];
      var index = list.indexOf(listener);
      if (index >= 0) {
        list.splice(index, 1);
      }
      var offName = mapping[1];
      if (typeof qg[offName] === 'function') {
        qg[offName](listener);
      }
    };
  }

  var memoryStorage = {};
  var storage = {
    getString: function (key) {
      try {
        if (typeof qg.getStorageSync === 'function') {
          var value = qg.getStorageSync(key);
          return typeof value === 'string' ? value : null;
        }
        if (root.localStorage) {
          return root.localStorage.getItem(key);
        }
      } catch (error) {
        warn('Storage get failed.', error);
      }
      return Object.prototype.hasOwnProperty.call(memoryStorage, key) ? memoryStorage[key] : null;
    },
    setString: function (key, value) {
      try {
        if (typeof qg.setStorageSync === 'function') {
          qg.setStorageSync(key, value);
          return;
        }
        if (root.localStorage) {
          root.localStorage.setItem(key, value);
          return;
        }
      } catch (error) {
        warn('Storage set failed.', error);
      }
      memoryStorage[key] = value;
    },
    remove: function (key) {
      try {
        if (typeof qg.removeStorageSync === 'function') {
          qg.removeStorageSync(key);
          return;
        }
        if (root.localStorage) {
          root.localStorage.removeItem(key);
          return;
        }
      } catch (error) {
        warn('Storage remove failed.', error);
      }
      delete memoryStorage[key];
    }
  };

  var muted = false;
  var sfxAudio = null;
  var musicAudio = null;

  function createAudioContext(label) {
    if (!qg || typeof qg.createInnerAudioContext !== 'function') {
      warn(label + ' audio API is unavailable.');
      return null;
    }
    var context = qg.createInnerAudioContext();
    if (context && typeof context.onError === 'function') {
      context.onError(function (error) {
        warn(label + ' audio playback failed.', error);
      });
    }
    return context;
  }

  function sfxPath(name) {
    return 'assets/audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.wav';
  }

  function musicPath(name) {
    return 'assets/audio/' + String(name).replace(/[^a-z0-9_-]/gi, '') + '.mp3';
  }

  var audio = {
    playSfx: function (name) {
      if (muted) {
        return Promise.resolve();
      }
      try {
        sfxAudio = sfxAudio || createAudioContext('SFX');
        if (!sfxAudio) {
          return Promise.resolve();
        }
        if (typeof sfxAudio.stop === 'function') {
          sfxAudio.stop();
        }
        sfxAudio.src = sfxPath(name);
        if (typeof sfxAudio.play === 'function') {
          sfxAudio.play();
        }
      } catch (error) {
        warn('SFX playback failed.', error);
      }
      return Promise.resolve();
    },
    playMusic: function (name, loop) {
      if (muted) {
        return Promise.resolve();
      }
      try {
        musicAudio = musicAudio || createAudioContext('Music');
        if (!musicAudio) {
          return Promise.resolve();
        }
        musicAudio.loop = Boolean(loop);
        musicAudio.src = musicPath(name);
        if (typeof musicAudio.play === 'function') {
          musicAudio.play();
        }
      } catch (error) {
        warn('Music playback failed.', error);
      }
      return Promise.resolve();
    },
    stopMusic: function () {
      if (musicAudio && typeof musicAudio.stop === 'function') {
        try {
          musicAudio.stop();
        } catch (error) {
          warn('Stopping music failed.', error);
        }
      }
    },
    setMuted: function (nextMuted) {
      muted = Boolean(nextMuted);
      if (muted) {
        this.stopMusic();
        if (sfxAudio && typeof sfxAudio.stop === 'function') {
          try {
            sfxAudio.stop();
          } catch (error) {
            warn('Stopping SFX audio failed.', error);
          }
        }
      }
    }
  };

  var rewardedVideoAd = null;
  function getRewardedVideoAd() {
    if (typeof qg.createRewardedVideoAd !== 'function') {
      return null;
    }
    if (!rewardedVideoAd) {
      rewardedVideoAd = qg.createRewardedVideoAd({});
      if (rewardedVideoAd && typeof rewardedVideoAd.onError === 'function') {
        rewardedVideoAd.onError(function (error) {
          warn('Rewarded video ad failed.', error);
        });
      }
    }
    return rewardedVideoAd;
  }

  var ads = {
    isRewardedVideoReady: function () {
      return typeof qg.createRewardedVideoAd === 'function';
    },
    showRewardedVideo: function () {
      var ad = getRewardedVideoAd();
      if (!ad) {
        warn('Rewarded video API is unavailable.');
        return Promise.resolve({ completed: false });
      }
      return new Promise(function (resolve) {
        var settled = false;
        function cleanup() {
          if (typeof ad.offClose === 'function') {
            ad.offClose(onClose);
          }
          if (typeof ad.offError === 'function') {
            ad.offError(onError);
          }
        }
        var onClose = function (result) {
          if (settled) return;
          settled = true;
          cleanup();
          resolve({ completed: Boolean(result && result.isEnded) });
        };
        var onError = function (error) {
          if (settled) return;
          settled = true;
          cleanup();
          warn('Rewarded video playback failed.', error);
          resolve({ completed: false });
        };
        if (typeof ad.onClose === 'function') {
          ad.onClose(onClose);
        }
        if (typeof ad.onError === 'function') {
          ad.onError(onError);
        }
        if (typeof ad.show !== 'function') {
          onError(new Error('Rewarded video show API unavailable.'));
          return;
        }
        try {
          Promise.resolve(ad.show()).catch(function () {
            if (typeof ad.load !== 'function') {
              onError(new Error('Rewarded video load API unavailable.'));
              return;
            }
            Promise.resolve(ad.load()).then(function () {
              return ad.show();
            }).catch(onError);
          });
        } catch (error) {
          onError(error);
        }
      });
    }
  };

  var rewards = {
    canAddDesktop: function () { return Promise.resolve(false); },
    requestAddDesktop: function () { return Promise.resolve(false); },
    canAddFavorite: function () { return Promise.resolve(false); },
    requestAddFavorite: function () { return Promise.resolve(false); },
    didEnterFromSidebar: function () { return Promise.resolve(false); },
    requestSidebarEntry: function () { return Promise.resolve(false); }
  };

  var haptics = {
    trigger: function (kind) {
      var apiName = kind === 'long' ? 'vibrateLong' : 'vibrateShort';
      var api = qg && qg[apiName];
      if (typeof api !== 'function') {
        warn('Haptic platform API unavailable.', { kind: kind, apiName: apiName });
        return;
      }
      try {
        api({
          success: function (result) {
            info('Haptic platform success.', { kind: kind, apiName: apiName, result: result });
          },
          fail: function (error) {
            warn('Haptic platform failed.', { kind: kind, apiName: apiName, error: error });
          }
        });
      } catch (error) {
        warn('Haptic platform threw.', { kind: kind, apiName: apiName, error: error });
      }
    }
  };

  var logger = {
    info: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.info === 'function') console.info(message, data);
    },
    warn: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.warn === 'function') console.warn(message, data);
    },
    error: function (message, data) {
      if (typeof console !== 'undefined' && typeof console.error === 'function') console.error(message, data);
    }
  };

  var createGame = __MiniPackGameBundle && __MiniPackGameBundle.createGame;
  if (typeof createGame !== 'function') {
    throw new Error('Game entry must export createGame(runtime).');
  }

  var app = createGame({
    canvas: createCanvas(),
    storage: storage,
    audio: audio,
    ads: ads,
    rewards: rewards,
    haptics: haptics,
    logger: logger
  });
  root.__MiniPackGameApp = app;
  app.start();
})();
`;
}
